from __future__ import annotations

import argparse
from html import escape
import json
from pathlib import Path
import shutil
import sys
import tempfile
from typing import Any, Mapping, Sequence, TextIO


SITE_ROOT = Path(__file__).resolve().parent
REPO_ROOT = SITE_ROOT.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

PAGES_DIR = SITE_ROOT / "pages"
TEMPLATES_DIR = SITE_ROOT / "templates"
ASSETS_DIR = SITE_ROOT / "assets"
DATA_DIR = SITE_ROOT / "data"
DEFAULT_OUTPUT = SITE_ROOT / "dist"
PUBLIC_SITE_DIR = REPO_ROOT / "public_site"
SOURCE_INVENTORY_DIR = REPO_ROOT / "control" / "inventory" / "sources"
MARKER_FILE = ".eureka-static-site-generated"

PAGE_ORDER = (
    "index",
    "status",
    "sources",
    "evals",
    "demo-queries",
    "limitations",
    "roadmap",
    "local-quickstart",
)
SOURCE_ORDER = (
    "synthetic-fixtures",
    "github-releases-recorded-fixtures",
    "internet-archive-recorded-fixtures",
    "local-bundle-fixtures",
    "article-scan-recorded-fixtures",
    "internet-archive-placeholder",
    "wayback-memento-placeholder",
    "software-heritage-placeholder",
    "local-files-placeholder",
)
REQUIRED_CLAIMS = (
    "Python reference backend prototype",
    "not production",
    "no scraping",
    "external baselines pending/manual",
    "placeholders remain placeholders",
)
PROHIBITED_CLAIMS = (
    "production ready",
    "live Google search",
    "live Internet Archive search",
    "native app available",
    "Rust production backend",
    "app store",
    "installer",
)


class BuildError(RuntimeError):
    pass


def main(argv: Sequence[str] | None = None, *, stdout: TextIO | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Build the stdlib static site into site/dist."
    )
    parser.add_argument(
        "--output",
        default=str(DEFAULT_OUTPUT),
        help="Directory to write generated static output into.",
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Remove previous generated output before building.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Build to a temporary directory and validate generated output.",
    )
    parser.add_argument("--json", action="store_true", help="Emit JSON summary.")
    args = parser.parse_args(list(argv) if argv is not None else None)

    output = stdout or sys.stdout
    try:
        if args.check:
            report = check_generated_site()
        else:
            report = build_site(Path(args.output), clean=args.clean)
        if args.json:
            output.write(json.dumps(report, indent=2, sort_keys=True) + "\n")
        else:
            output.write(_format_plain(report))
        return 0 if report["status"] == "valid" else 1
    except BuildError as exc:
        report = {
            "status": "invalid",
            "created_by": "static_site_generation_migration_v0",
            "errors": [str(exc)],
        }
        if args.json:
            output.write(json.dumps(report, indent=2, sort_keys=True) + "\n")
        else:
            output.write(_format_plain(report))
        return 1


def build_site(output_dir: Path = DEFAULT_OUTPUT, *, clean: bool = False) -> dict[str, Any]:
    output_dir = output_dir.resolve()
    if output_dir == PUBLIC_SITE_DIR.resolve():
        raise BuildError(
            "refusing to write directly to public_site; this milestone keeps public_site as "
            "the deployment artifact and generated output under site/dist."
        )
    if clean:
        _clean_output_dir(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    page_configs = load_page_configs()
    templates = _load_templates()
    source_records = load_source_records()

    rendered_pages: list[str] = []
    for page in page_configs:
        html = render_page(page, page_configs, templates, source_records)
        output_path = output_dir / str(page["output_path"])
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(html, encoding="utf-8")
        rendered_pages.append(str(page["output_path"]))

    assets_output = output_dir / "assets"
    assets_output.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(ASSETS_DIR / "site.css", assets_output / "site.css")
    (assets_output / "README.md").write_text(_asset_readme(), encoding="utf-8")
    (output_dir / "README.md").write_text(_output_readme(), encoding="utf-8")
    (output_dir / MARKER_FILE).write_text(
        "Generated by Static Site Generation Migration v0.\n",
        encoding="utf-8",
    )
    manifest = build_manifest(rendered_pages)
    (output_dir / "site_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    public_data_report = _write_public_data(output_dir / "data")
    compatibility_report = _write_compatibility_surfaces(output_dir, output_dir / "data")
    demo_report = _write_static_resolver_demos(output_dir, output_dir / "data")

    return {
        "status": "valid",
        "created_by": "static_site_generation_migration_v0",
        "source_root": "site",
        "output_dir": _display_path(output_dir),
        "deploy_artifact_current": "public_site",
        "generated_output_deployed": False,
        "pages": rendered_pages,
        "public_data_files": public_data_report["data_files"],
        "compatibility_surface_files": compatibility_report["files"],
        "static_resolver_demo_files": demo_report["files"],
        "source_records": [record["source_id"] for record in source_records],
        "no_network_required": True,
        "no_deployment_performed": True,
        "errors": [],
    }


def check_generated_site() -> dict[str, Any]:
    from scripts.validate_public_static_site import validate_public_static_site

    errors: list[str] = []
    with tempfile.TemporaryDirectory(prefix="eureka-site-check-") as temp_dir:
        output_dir = Path(temp_dir) / "dist"
        build_report = build_site(output_dir)
        validation_report = validate_public_static_site(output_dir)
        if validation_report["status"] != "valid":
            errors.extend(
                f"generated static-site validator: {error}"
                for error in validation_report["errors"]
            )
        public_manifest = _load_json(PUBLIC_SITE_DIR / "site_manifest.json")
        generated_manifest = _load_json(output_dir / "site_manifest.json")
        public_pages = sorted(public_manifest.get("pages", []))
        generated_pages = sorted(generated_manifest.get("pages", []))
        if public_pages != generated_pages:
            errors.append(
                f"generated pages {generated_pages} do not match public_site pages {public_pages}."
            )
        for page in generated_manifest.get("pages", []):
            generated = output_dir / page
            if not generated.exists():
                errors.append(f"generated page missing: {page}")
        return {
            "status": "valid" if not errors else "invalid",
            "created_by": "static_site_generation_migration_v0",
            "check_mode": True,
            "source_root": "site",
            "deploy_artifact_current": "public_site",
            "generated_output_deployed": False,
            "build": build_report,
            "static_site_validation": validation_report,
            "errors": errors,
        }


def load_page_configs() -> list[dict[str, Any]]:
    configs: list[dict[str, Any]] = []
    for slug in PAGE_ORDER:
        path = PAGES_DIR / f"{slug}.json"
        payload = _load_json(path)
        if not isinstance(payload, dict):
            raise BuildError(f"{_display_path(path)} must contain a JSON object.")
        missing = {
            "slug",
            "output_path",
            "title",
            "heading",
            "summary",
            "sections",
            "links",
            "required_claims",
            "status",
        } - set(payload)
        if missing:
            raise BuildError(f"{_display_path(path)} missing required fields: {sorted(missing)}.")
        if payload["slug"] != slug:
            raise BuildError(f"{_display_path(path)} slug must be {slug!r}.")
        if not isinstance(payload["sections"], list):
            raise BuildError(f"{_display_path(path)} sections must be a list.")
        configs.append(payload)
    return configs


def load_source_records() -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for path in sorted(SOURCE_INVENTORY_DIR.glob("*.source.json")):
        payload = _load_json(path)
        if not isinstance(payload, dict):
            raise BuildError(f"{_display_path(path)} must contain a JSON object.")
        source_id = payload.get("source_id")
        if not isinstance(source_id, str):
            raise BuildError(f"{_display_path(path)} missing string source_id.")
        records.append(payload)
    order = {source_id: index for index, source_id in enumerate(SOURCE_ORDER)}
    return sorted(records, key=lambda record: order.get(str(record["source_id"]), 1000))


def render_page(
    page: Mapping[str, Any],
    all_pages: Sequence[Mapping[str, Any]],
    templates: Mapping[str, str],
    source_records: Sequence[Mapping[str, Any]],
) -> str:
    content = "\n".join(render_section(section, source_records) for section in page["sections"])
    content = templates["page"].replace("{{ content }}", content)
    lede = ""
    if page.get("summary"):
        lede = f'<p class="lede">{escape(str(page["summary"]))}</p>'
    html = templates["base"]
    replacements = {
        "{{ title }}": escape(str(page["title"])),
        "{{ heading }}": escape(str(page["heading"])),
        "{{ lede }}": lede,
        "{{ nav }}": render_nav(all_pages),
        "{{ content }}": content,
    }
    for marker, value in replacements.items():
        html = html.replace(marker, value)
    return "\n".join(line.rstrip() for line in html.splitlines()) + "\n"


def render_nav(all_pages: Sequence[Mapping[str, Any]]) -> str:
    lines = []
    labels = {
        "index": "Overview",
        "demo-queries": "Demo Queries",
        "local-quickstart": "Local Quickstart",
    }
    for page in all_pages:
        slug = str(page["slug"])
        label = labels.get(slug, str(page["heading"]))
        lines.append(f'      <a href="{escape(str(page["output_path"]))}">{escape(label)}</a>')
    return "\n".join(lines)


def render_section(
    section: Mapping[str, Any], source_records: Sequence[Mapping[str, Any]]
) -> str:
    section_type = section.get("type")
    if section_type == "notice":
        return f'    <section class="notice">\n      {escape(str(section["text"]))}\n    </section>'
    if section_type == "paragraph":
        return f'    <p>{escape(str(section["text"]))}</p>'
    if section_type == "heading":
        level = int(section.get("level", 2))
        if level not in (2, 3):
            level = 2
        return f'    <h{level}>{escape(str(section["text"]))}</h{level}>'
    if section_type == "pre":
        return f'    <pre><code>{escape(str(section["text"]))}</code></pre>'
    if section_type == "list":
        items = "\n".join(f"      <li>{escape(str(item))}</li>" for item in section["items"])
        return f"    <ul>\n{items}\n    </ul>"
    if section_type == "ordered":
        items = []
        for item in section["items"]:
            title = escape(str(item["title"]))
            text = escape(str(item["text"]))
            items.append(f"      <li><strong>{title}</strong>: {text}</li>")
        return "    <ol>\n" + "\n".join(items) + "\n    </ol>"
    if section_type == "grid":
        panels = "\n".join(render_panel(panel) for panel in section["panels"])
        return f'    <section class="grid">\n{panels}\n    </section>'
    if section_type == "table":
        return render_table(section["headers"], section["rows"])
    if section_type == "source_matrix":
        return render_source_matrix(source_records)
    raise BuildError(f"unknown section type: {section_type!r}")


def render_panel(panel: Mapping[str, Any]) -> str:
    lines = ['      <div class="panel">', f'        <h2>{escape(str(panel["title"]))}</h2>']
    for paragraph in panel.get("paragraphs", []):
        lines.append(f"        <p>{escape(str(paragraph))}</p>")
    if panel.get("links"):
        lines.append("        <ul>")
        for link in panel["links"]:
            lines.append(
                f'          <li><a href="{escape(str(link["href"]))}">{escape(str(link["text"]))}</a></li>'
            )
        lines.append("        </ul>")
    lines.append("      </div>")
    return "\n".join(lines)


def render_table(headers: Sequence[str], rows: Sequence[Sequence[str]]) -> str:
    header_html = "\n".join(f"          <th>{escape(str(header))}</th>" for header in headers)
    row_html = []
    for row in rows:
        cells = "\n".join(f"          <td>{escape(str(cell))}</td>" for cell in row)
        row_html.append(f"        <tr>\n{cells}\n        </tr>")
    return (
        "    <table>\n"
        "      <thead>\n"
        "        <tr>\n"
        f"{header_html}\n"
        "        </tr>\n"
        "      </thead>\n"
        "      <tbody>\n"
        + "\n".join(row_html)
        + "\n      </tbody>\n"
        "    </table>"
    )


def render_source_matrix(source_records: Sequence[Mapping[str, Any]]) -> str:
    headers = [
        "source_id",
        "Label",
        "Family",
        "Posture / status",
        "Coverage depth",
        "Fixture / live / manual state",
        "Capabilities summary",
        "Current limitations",
        "Next coverage step",
    ]
    rows: list[list[str]] = []
    for record in source_records:
        coverage = _mapping(record.get("coverage"))
        rows.append(
            [
                f"<code>{escape(str(record['source_id']))}</code>",
                escape(str(record.get("name", record["source_id"]))),
                escape(str(record.get("source_family", "unknown"))),
                escape(str(record.get("status", "unknown"))),
                escape(str(coverage.get("coverage_depth", "unknown"))),
                escape(_fixture_live_state(record)),
                escape(_capabilities_summary(record)),
                escape(_limitations_summary(record)),
                escape(str(coverage.get("next_coverage_step", "Future governed coverage review."))),
            ]
        )
    header_html = "\n".join(f"          <th>{escape(header)}</th>" for header in headers)
    row_html = []
    for row in rows:
        cells = "\n".join(f"          <td>{cell}</td>" for cell in row)
        row_html.append(f"        <tr>\n{cells}\n        </tr>")
    return (
        "    <table>\n"
        "      <thead>\n"
        "        <tr>\n"
        f"{header_html}\n"
        "        </tr>\n"
        "      </thead>\n"
        "      <tbody>\n"
        + "\n".join(row_html)
        + "\n      </tbody>\n"
        "    </table>"
    )


def build_manifest(pages: Sequence[str]) -> dict[str, Any]:
    return {
        "site_pack_id": "live_alpha_static_public_site_pack_v0",
        "generated_or_authored_by_slice": "static_site_generation_migration_v0",
        "generated_by": "site/build.py",
        "generated_at": "STATIC_SITE_GENERATION_MIGRATION_V0_STABLE_BUILD",
        "source_root": "site",
        "artifact_root": "site/dist",
        "deploy_artifact_current": "public_site",
        "generated_output_deployed": False,
        "pages": list(pages),
        "required_claims": list(REQUIRED_CLAIMS),
        "prohibited_claims": list(PROHIBITED_CLAIMS),
        "source_matrix_source": "control/inventory/sources/*.source.json",
        "eval_status_source": "static page JSON with references to scripts/run_archive_resolution_evals.py and scripts/run_search_usefulness_audit.py",
        "public_data_source": "scripts/generate_public_data_summaries.py",
        "public_data_files": [
            "data/site_manifest.json",
            "data/page_registry.json",
            "data/source_summary.json",
            "data/eval_summary.json",
            "data/route_summary.json",
            "data/build_manifest.json",
        ],
        "compatibility_surfaces": [
            "lite/",
            "text/",
            "files/",
        ],
        "compatibility_surface_source": "scripts/generate_compatibility_surfaces.py",
        "static_resolver_demos": [
            "demo/",
        ],
        "static_resolver_demo_source": "scripts/generate_static_resolver_demos.py",
        "custom_domain_readiness_source": "scripts/validate_static_host_readiness.py",
        "domain_plan_source": "control/inventory/publication/domain_plan.json",
        "static_hosting_targets_source": "control/inventory/publication/static_hosting_targets.json",
        "live_backend_handoff_source": "control/inventory/publication/live_backend_handoff.json",
        "live_backend_routes_source": "control/inventory/publication/live_backend_routes.json",
        "live_probe_gateway_source": "control/inventory/publication/live_probe_gateway.json",
        "surface_capabilities_source": "control/inventory/publication/surface_capabilities.json",
        "snapshot_contract_source": "control/inventory/publication/snapshot_contract.json",
        "snapshot_seed_example_root": "snapshots/examples/static_snapshot_v0",
        "snapshot_public_route_enabled": False,
        "limitations": [
            "static only",
            "no deployment performed",
            "no backend hosting added",
            "no live source probes",
            "/api/v1 reserved only; not live",
            "live probe gateway contract-only; no probes implemented",
            "Google manual baseline only",
            "no production API guarantee",
            "no custom domain configured",
            "no DNS changes performed",
            "no CNAME file committed",
            "no public /snapshots/ route",
            "no production signed snapshots",
            "no real signing keys",
            "no executable downloads",
            "no scraping",
            "manual external baselines remain pending",
            "fixture-backed evidence is not global truth",
        ],
        "publication_contract_source": "control/inventory/publication/publication_contract.json",
        "github_pages_target": "github_pages_project",
        "github_pages_base_path": "/eureka/",
        "deployment_workflow_configured": True,
        "deployment_status": "workflow_configured_deployment_unverified",
        "static_only": True,
        "no_backend": True,
        "no_live_backend": True,
        "no_live_probes": True,
        "live_backend_handoff_contract_only": True,
        "api_v1_reserved": True,
        "api_v1_live": False,
        "live_probe_gateway_contract_only": True,
        "live_probes_enabled": False,
        "internet_archive_live_probe_enabled": False,
        "arbitrary_url_fetch_enabled": False,
        "downloads_enabled": False,
        "production_signed_snapshots_available": False,
        "real_signing_keys_present": False,
        "public_snapshots_route_enabled": False,
        "no_custom_domain_configured": True,
        "no_dns_changes_performed": True,
        "no_cname_file_committed": True,
        "base_path_targets": [
            "/eureka/",
            "/",
        ],
        "next_milestone": "Relay Surface Design v0",
        "parallel_human_work": "Manual Observation Batch 0 Execution",
        "no_network_required": True,
        "no_deployment_performed": True,
    }


def _write_public_data(output_root: Path) -> Mapping[str, Any]:
    from scripts.generate_public_data_summaries import write_public_data_summaries

    return write_public_data_summaries(output_root)


def _write_compatibility_surfaces(output_root: Path, data_root: Path) -> Mapping[str, Any]:
    from scripts.generate_compatibility_surfaces import write_compatibility_surfaces

    return write_compatibility_surfaces(output_root, data_root)


def _write_static_resolver_demos(output_root: Path, data_root: Path) -> Mapping[str, Any]:
    from scripts.generate_static_resolver_demos import write_static_resolver_demos

    return write_static_resolver_demos(output_root, data_root)


def _fixture_live_state(record: Mapping[str, Any]) -> str:
    status = str(record.get("status", ""))
    capabilities = _mapping(record.get("capabilities"))
    live_access = _mapping(record.get("live_access"))
    if status == "placeholder":
        return "Planning placeholder only; no connector or live access."
    if status == "local_private_future":
        return "Future local/private source only; no current local-files ingestion."
    if capabilities.get("recorded_fixture_backed"):
        return "Recorded fixtures only; no live network access."
    if capabilities.get("fixture_backed"):
        return "Committed local fixture only; no live network access."
    return str(live_access.get("notes", "No live state is claimed."))


def _capabilities_summary(record: Mapping[str, Any]) -> str:
    capabilities = _mapping(record.get("capabilities"))
    labels = [
        ("supports_search", "search"),
        ("supports_item_metadata", "item metadata"),
        ("supports_file_listing", "file listing"),
        ("supports_member_listing", "member listing"),
        ("supports_content_text", "content text"),
        ("supports_hashes", "hashes"),
        ("supports_action_paths", "action paths"),
        ("supports_temporal_captures", "temporal captures"),
        ("supports_live_probe", "live probes"),
    ]
    supported = [label for key, label in labels if capabilities.get(key)]
    if not supported:
        return "No current search, metadata, file listing, member listing, or live probe capability."
    return ", ".join(supported).capitalize() + "."


def _limitations_summary(record: Mapping[str, Any]) -> str:
    coverage = _mapping(record.get("coverage"))
    limitations = coverage.get("current_limitations")
    if isinstance(limitations, list) and limitations:
        return "; ".join(str(item) for item in limitations)
    return str(coverage.get("coverage_notes", "Fixture and placeholder boundaries remain governed."))


def _mapping(value: Any) -> Mapping[str, Any]:
    return value if isinstance(value, Mapping) else {}


def _load_templates() -> dict[str, str]:
    return {
        "base": (TEMPLATES_DIR / "base.html").read_text(encoding="utf-8"),
        "page": (TEMPLATES_DIR / "page.html").read_text(encoding="utf-8"),
    }


def _load_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise BuildError(f"missing JSON source: {_display_path(path)}") from exc
    except json.JSONDecodeError as exc:
        raise BuildError(f"invalid JSON source {_display_path(path)}: {exc}") from exc


def _clean_output_dir(output_dir: Path) -> None:
    if not output_dir.exists():
        return
    default_output = DEFAULT_OUTPUT.resolve()
    is_default = output_dir.resolve() == default_output
    marker_exists = (output_dir / MARKER_FILE).exists()
    is_empty = output_dir.is_dir() and not any(output_dir.iterdir())
    if not (is_default or marker_exists or is_empty):
        raise BuildError(
            f"refusing to clean non-generated output without {MARKER_FILE}: {_display_path(output_dir)}"
        )
    if output_dir.is_dir():
        shutil.rmtree(output_dir)
    else:
        output_dir.unlink()


def _asset_readme() -> str:
    return (
        "# Static Assets\n\n"
        "Generated static assets for the stdlib site output.\n"
    )


def _output_readme() -> str:
    return (
        "# Generated Static Site Output\n\n"
        "This directory is generated by `python site/build.py`.\n\n"
        "`data/` is generated by Generated Public Data Summaries v0 for static "
        "validation only; it is not a live API.\n\n"
        "`lite/`, `text/`, and `files/` are generated by Lite/Text/Files Seed "
        "Surfaces v0 for static compatibility validation; they do not add live "
        "search, downloads, snapshots, relay behavior, or native-client runtime.\n\n"
        "`demo/` is generated by Static Resolver Demo Snapshots v0 for static "
        "fixture-backed resolver examples; it does not add live search, a live "
        "API, backend hosting, external observations, or production behavior.\n\n"
        "`public_site/` remains the GitHub Pages deployment artifact for Static "
        "Site Generation Migration v0.\n"
    )


def _format_plain(report: Mapping[str, Any]) -> str:
    lines = [
        "Static site generator",
        f"status: {report['status']}",
        f"source_root: {report.get('source_root', 'site')}",
    ]
    if report.get("output_dir"):
        lines.append(f"output_dir: {report['output_dir']}")
    if report.get("deploy_artifact_current"):
        lines.append(f"deploy_artifact_current: {report['deploy_artifact_current']}")
    if report.get("pages"):
        lines.append(f"pages: {len(report['pages'])}")
    if report.get("errors"):
        lines.append("")
        lines.append("Errors")
        lines.extend(f"- {error}" for error in report["errors"])
    return "\n".join(lines) + "\n"


def _display_path(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(REPO_ROOT)).replace("\\", "/")
    except ValueError:
        return str(path)


if __name__ == "__main__":
    raise SystemExit(main())
