"""Server-facing helpers for the bootstrap Eureka web workbench."""

from surfaces.web.server.api_routes import build_api_index_document
from surfaces.web.server.public_alpha_config import (
    PublicAlphaWrapperConfig,
    load_public_alpha_wrapper_config,
)
from surfaces.web.server.route_policy import PublicAlphaRoutePolicy, RoutePolicyDecision
from surfaces.web.server.server_config import WebServerConfig, default_web_server_config
from surfaces.web.server.workbench_server import (
    WorkbenchWsgiApp,
    render_action_plan_page,
    render_resolve_absence_page,
    render_search_absence_page,
    render_decomposition_page,
    render_member_access_page,
    render_bundle_inspection_page,
    render_compatibility_page,
    render_comparison_page,
    render_handoff_page,
    render_local_index_page,
    render_resolution_memory_page,
    render_create_resolution_memory_page,
    render_local_tasks_page,
    render_query_plan_page,
    render_representations_page,
    render_resolution_runs_page,
    render_resolution_workspace_page,
    render_exact_resolution_run_page,
    render_deterministic_search_run_page,
    render_planned_search_run_page,
    render_validate_archive_resolution_evals_task_page,
    render_validate_source_registry_task_page,
    render_build_local_index_task_page,
    render_query_local_index_task_page,
    render_search_results_page,
    render_source_registry_page,
    render_subject_states_page,
)

__all__ = [
    "WorkbenchWsgiApp",
    "PublicAlphaRoutePolicy",
    "PublicAlphaWrapperConfig",
    "RoutePolicyDecision",
    "WebServerConfig",
    "build_api_index_document",
    "default_web_server_config",
    "load_public_alpha_wrapper_config",
    "render_action_plan_page",
    "render_resolve_absence_page",
    "render_search_absence_page",
    "render_decomposition_page",
    "render_member_access_page",
    "render_bundle_inspection_page",
    "render_compatibility_page",
    "render_comparison_page",
    "render_handoff_page",
    "render_local_index_page",
    "render_resolution_memory_page",
    "render_create_resolution_memory_page",
    "render_local_tasks_page",
    "render_query_plan_page",
    "render_representations_page",
    "render_resolution_runs_page",
    "render_resolution_workspace_page",
    "render_exact_resolution_run_page",
    "render_deterministic_search_run_page",
    "render_planned_search_run_page",
    "render_validate_archive_resolution_evals_task_page",
    "render_validate_source_registry_task_page",
    "render_build_local_index_task_page",
    "render_query_local_index_task_page",
    "render_search_results_page",
    "render_source_registry_page",
    "render_subject_states_page",
]
