"""Server-rendered local workbench pages."""

from .html import (
    escape_html,
    render_document,
    render_limitations,
    render_link,
    render_notice,
    render_table,
    render_warnings,
)
from .pages import (
    render_absence_page,
    render_home_page,
    render_object_page,
    render_search_page,
    render_source_page,
    render_status_page,
)
from .validation import (
    validate_html_safe,
    validate_local_workbench_page,
    validate_no_external_assets,
    validate_no_mutation_controls,
    validate_required_accessibility_markers,
)
from .view_models import (
    AbsencePageView,
    HomePageView,
    ObjectPageView,
    SearchPageView,
    SourcePageView,
    StatusPageView,
    build_absence_page_view,
    build_home_page_view,
    build_object_page_view,
    build_search_page_view,
    build_source_page_view,
    build_status_page_view,
)

__all__ = [
    "AbsencePageView",
    "HomePageView",
    "ObjectPageView",
    "SearchPageView",
    "SourcePageView",
    "StatusPageView",
    "build_absence_page_view",
    "build_home_page_view",
    "build_object_page_view",
    "build_search_page_view",
    "build_source_page_view",
    "build_status_page_view",
    "escape_html",
    "render_absence_page",
    "render_document",
    "render_home_page",
    "render_limitations",
    "render_link",
    "render_notice",
    "render_object_page",
    "render_search_page",
    "render_source_page",
    "render_status_page",
    "render_table",
    "render_warnings",
    "validate_html_safe",
    "validate_local_workbench_page",
    "validate_no_external_assets",
    "validate_no_mutation_controls",
    "validate_required_accessibility_markers",
]
